USE master;
GO

IF EXISTS(SELECT name FROM master.sys.databases WHERE name = 'SOUNDSTAGE_DB')
	DROP DATABASE SOUNDSTATE_DB
GO

CREATE DATABASE SOUNDSTAGE_DB;
GO

USE SOUNDSTAGE_DB;
GO

CREATE TABLE SOUND(
	soundID		Int				NOT NULL IDENTITY(1,1),
	filePath	VarChar(300)	NOT NULL,
	isBackup	Bit				NOT NULL,
	name		VarChar(100)	NULL,
	CONSTRAINT	SOUND_PK		PRIMARY KEY(soundID)
);

CREATE TABLE KEYBINDS(
	bindID		Int				NOT NULL IDENTITY(1,1),
	keys		VarChar(50)		NOT NULL,
	soundID		Int				NOT NULL,
	CONSTRAINT KEY_PK			PRIMARY KEY(bindID),
	CONSTRAINT KEY_SOUND_FK		FOREIGN KEY(soundID)
							REFERENCES SOUND(soundID)
							ON DELETE CASCADE
);

CREATE TABLE BUTTONBINDS(
	bindID		Int				NOT NULL IDENTITY(1,1),
	soundID		Int				NOT NULL,
	CONSTRAINT BUTTON_PK		PRIMARY KEY(bindID),
	CONSTRAINT BUTTON_SOUND_FK	FOREIGN KEY(soundID)
							REFERENCES SOUND(soundID)
							ON DELETE CASCADE
);